
services:
  database:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - app-network
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: library_user
      PMA_PASSWORD: library_password
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend-service
    environment:
      DATABASE_URL: mysql+pymysql://library_user:library_password@database:3306/library
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
